max_width = 80
tab_spaces = 2
newline_style = "Unix"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
use_field_init_shorthand = true
# Outdated default, the `try!` macro is deprecated now.
use_try_shorthand = true
# Allow all things to be max width.
use_small_heuristics = "Max"

# Unstable features
wrap_comments = true
format_code_in_doc_comments = true
comment_width = 80
format_strings = true
hex_literal_case = "Upper"
where_single_line = true
combine_control_expr = false

# Prevents fighting with format on save.
empty_item_single_line = false

# Import organization
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
